
name: Atmosphere Builder 2.0

on: [push]
jobs:
  Atmosphere:
    runs-on: ubuntu-latest
    container: d3fau4/atmosphere-builder
    steps:
    - uses: actions/checkout@v1
    - name: Update repo.
      run: |
        git submodule update --init --recursive
    
- name: Download Sept patch
      run: |
        wget -P sept/sept-secondary/ http://illegalshit.tk/sept/sept-secondary_00.enc
        wget -P sept/sept-secondary/ http://illegalshit.tk/sept/sept-secondary_01.enc
        wget -P sept/sept-secondary/ http://illegalshit.tk/sept/sept-secondary_dev_00.enc
        wget -P sept/sept-secondary/ http://illegalshit.tk/sept/sept-secondary_dev_01.enc

    - name: Building Atmosphere
      run: |
        make dist-no-debug -j$(nproc)

    - uses: actions/upload-artifact@master
      with:
        name: Atmophere
        path: out/