
name: Build Atmosphère

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update repo.
      run: |
        git submodule update --init --recursive
        
    - name: Install devkitpro
      run: |
        wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
        sudo dpkg -i devkitpro-pacman.deb
        sudo dkp-pacman -S $(dkp-pacman -Ssq switch-*) --noconfirm
        sudo dkp-pacman -S devkit-env  devkitARM  devkitarm-crtls devkitarm-rules --noconfirm
        
    - name: Download Sept patch
      run: |
        rm sept/sept-secondary/Makefile
        wget -P sept/sept-secondary/ http://illegalshit.tk/sept/Makefile
        wget -P sept/sept-secondary/ http://illegalshit.tk/sept/sept-secondary_00.enc
        wget -P sept/sept-secondary/ http://illegalshit.tk/sept/sept-secondary_01.enc
      
    - name: Building Atmosphere
      run: |
        echo ##########################
        echo #     SETTING PATH       #
        echo ##########################
        echo
        export DEVKITPRO=/opt/devkitpro
        export DEVKITARM=${DEVKITPRO}/devkitARM
        export DEVKITPPC=${DEVKITPRO}/devkitPPC
        export PATH=${DEVKITPRO}/tools/bin:$PATH
        make dist -j$(nproc)
        
    - uses: actions/upload-artifact@master
      with:
        name: Build
        path: out/